# File: .github/workflows/addbranding.yml
name: brandrepo

on:
  push:
    branches:
      - copyover

jobs:
  branding_test:
    name: brand repo
    runs-on: ubuntu-latest
    steps:
      - name: get github repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: "copyover"
      - name: Find and Replace EVO WITH UP
        uses: jacobtomlinson/gha-find-replace@0.1.1
        with:
          include: "README.md"
          find: "EVO"
          replace: "UniversalPay"
      - name: Find and Replace Evo Gateway WITH UniversalPay Gateway
        uses: jacobtomlinson/gha-find-replace@0.1.1
        with:
          include: "README.md"
          find: "Evo Gateway"
          replace: "UniversalPay Gateway"
      - name: add to github
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "testing testing 123"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: copyover
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
  copytomaster:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v1
      env:
        SOURCE_REPO: ${{ github.repository }}
        SOURCE_BRANCH: "copyover"
        DESTINATION_REPO: ${{ github.repository }}
        DESTINATION_BRANCH: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH
