# File: .github/workflows/addbranding.yml
name: brandrepo

on:
  push:
    branches:
      - copyover

jobs:
  branding_test:
    name: brand repo
    runs-on: ubuntu-latest
    steps:
      - name: get github repo
        uses: actions/checkout@v2
        with: 
          repository: ${{ github.repository }}
          ref: 'copyover'      
      - name: Find and Replace EVO WITH UP
        uses: jacobtomlinson/gha-find-replace@0.1.1
        with:
          include: "README.md"
          find: "EVO"
          replace: "UniversalPay"
      - name: Find and Replace Evo Gateway WITH UniversalPay Gateway
        uses: jacobtomlinson/gha-find-replace@0.1.1
        with:
          include: "README.md"
          find: "Evo Gateway"
          replace: "UniversalPay Gateway"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Brand Repo"
          labels: autopr
          body: |
            A new version has been detected and branded version generated.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge by labeled
        uses: devmasx/merge-branch@v1.1.0
        with:
          label_name: 'autopr'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}