# File: .github/workflows/addbranding.yml
name: brandrepo

on:
  push:
    branches:
      - master

jobs:
  branding_test_UP:
    name: brand repo
    runs-on: ubuntu-latest
    if: github.repository == 'intelligentpayments/PHP_SDK_UP'
    steps:
      - name: get github repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: "master"
      - name: Find and Replace EVO WITH 'intelligentpayments/PHP_SDK_UP'
        uses: jacobtomlinson/gha-find-replace@0.1.1
        with:
          include: "README.md"
          find: "EVO"
          replace: "UniversalPay"
      - name: Find and Replace Evo Gateway WITH UniversalPay Gateway
        uses: jacobtomlinson/gha-find-replace@0.1.1
        with:
          include: "README.md"
          find: "Evo Gateway"
          replace: "UniversalPay Gateway"
      - name: Add to GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "testing testing 123"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
  sync_to_public_repo_eurobic:
    needs: branding_test_UP
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v1
      env:
        SOURCE_REPO: "git@github.com:intelligentpayments/PHP_SDK_UP.git"
        SOURCE_BRANCH: "master"
        DESTINATION_REPO: "git@github.com:Eurobic/PHP_SDK.git"
        DESTINATION_BRANCH: "master"
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH

  branding_test_BOIPA:
    name: brand repo
    runs-on: ubuntu-latest
    if: github.repository == 'intelligentpayments/PHP_SDK_BOIPA'
    steps:
      - name: get github repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: "master"
      - name: Find and Replace EVO WITH BOIPA
        uses: jacobtomlinson/gha-find-replace@0.1.1
        with:
          include: "README.md"
          find: "EVO"
          replace: "BOIPA"
      - name: Find and Replace Evo Gateway WITH BOIPA Gateway
        uses: jacobtomlinson/gha-find-replace@0.1.1
        with:
          include: "README.md"
          find: "Evo Gateway"
          replace: "BOIPA Gateway"
      - name: add to github
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "testing testing 123"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      