# File: .github/workflows/pushtoprod.yml
name: push to prod
on:
  pull_request:
    - opened
    - edited
jobs:
  synctomaster:
    runs-on: ubuntu-latest
    steps:
      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: 1
          method: squash