# File: .github/workflows/pushtoprod.yml
name: pushtoprod
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/1 * * * *'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge by labeled
        uses: devmasx/merge-branch@v1.1.0
        with:
          label_name: 'autopr'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}